config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    resources :products,            only: :show
    resources :categories,          only: :show
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potepan/product_decorator.rb
module Potepan::ProductDecorator
  def related_products
    Spree::Product.
      in_taxons(taxons).
      where.not(id: id).
      distinct
  end
  Spree::Product.prepend self
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @products = Spree::Product.includes(master: [:images, :default_price]).in_taxon(@taxon)
    @taxonomies = Spree::Taxonomy.includes(:root)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_RELATED_PRODUCTS_COUNT = 4
  def show
    @product = Spree::Product.find(params[:id])
    @related_products = @product.related_products.
      includes(master: [:default_price, :images]).
      limit(MAX_RELATED_PRODUCTS_COUNT)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BASE_TITLE = 'BIGBAG Store'.freeze
  def full_title(page_title = "")
    if page_title.blank?
      BASE_TITLE
    else
      "#{page_title} - #{BASE_TITLE}"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <%= render 'layouts/top_bar' %>
  <!-- NAVBAR -->
  <%= render 'layouts/nav_bar' %>
</div>

app/views/layouts/_login_modal.html.erb
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">ログイン</h3>
      </div>
      <div class="modal-body">
        <form action="login-" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">メールアドレス</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">パスワード</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> 記憶しておく
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">ログイン</button>
          <a href="lost-password.html" class="btn btn-link btn-block">パスワードをお忘れの方</a>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-main navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/potepan"></a>
      <%= link_to(image_tag("img/logo.png", :alt => ""), potepan_path, class: "navbar-brand") %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', potepan_path %></li>
        <li class="dropdown megaDropMenu active">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
        </li>        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/_partners_logo.html.erb
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_product_quick_view_modal.html.erb
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>149円</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_right_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= product_name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to 'Home', potepan_path %>
          </li>
          <li class="active"><%= product_name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_sign_up_modal.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">新規登録</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">メールアドレス</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">パスワード</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">パスワード（確認用）</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">登録する</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_top_bar.html.erb
<!-- TOPBAR -->
<div class="topBar">
  <div class="container">
    <div class="row">
      <div class="col-md-6 hidden-sm hidden-xs">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
      <div class="col-md-6 col-xs-12">
        <ul class="list-inline pull-right">
          <li class="dropdown searchBox">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li>
                <span class="input-group">
                  <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                  <span class="input-group-addon" id="basic-addon2">Search</span>
                </span>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="/potepan/cart_page" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/sign_up_modal' %>
    <%= render 'layouts/product_quick_view_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <%= link_to potepan_product_path(product.id) do %>
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag(product.display_image.attachment(:large), alt: "sample-image") %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/_sidebar_left.html.erb
<% taxonomies.each do |taxonomy| %>
  <li>
    <a href="javascript:;" data-toggle="collapse" data-target="#<%= taxonomy.id %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
    <ul id="<%= taxonomy.id %>" class="collapse collapseItem">
      <% taxonomy.root.leaves.each do |taxon| %>
        <li><%= link_to potepan_category_path(taxon.id) do %><i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %><span>(<%= taxon.products.count %>)</span></li><% end %>
      <% end %>
    </ul>
  </li>
<% end %>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to 'Home', potepan_path %>
          </li>
          <li>
            <%= link_to 'Shop', '#' %>
          </li>
          <li class="active"><%= @taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <div class="panel panel-default">
          <div class="panel-heading">商品カテゴリー</div>
          <div class="panel-body">
            <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
              <ul id="category" class="nav navbar-nav side-nav">
                <%= render 'sidebar_left', taxonomies: @taxonomies %>
              </ul>
            </div>
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">色から探す</div>
          <div class="panel-body">
            <ul class="list-unstyled">
              <li><a href="#">ブラック<span>(15)</span></a></li>
              <li><a href="#">ホワイト<span>(10)</span></a></li>
              <li><a href="#">レッド<span>(7)</span></a></li>
              <li><a href="#">ブルー<span>(12)</span></a></li>
              <li><a href="#">オレンジ<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">サイズから探す</div>
          <div class="panel-body">
            <ul class="list-unstyled clearfix">
              <li><a href="#">S<span>(15)</span></a></li>
              <li><a href="#">M<span>(10)</span></a></li>
              <li><a href="#">L<span>(7)</span></a></li>
              <li><a href="#">XL<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <select name="guiest_id1" id="guiest_id1" class="select-drop">
              <option value="0">並び替え</option>
              <option value="1">人気順</option>
              <option value="2">安い順</option>
              <option value="3">新着順</option>
              <option value="3">高い順</option>
            </select>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row">
          <%= render partial: "product", collection: @products %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/partners_logo' %>

app/views/potepan/products/_related_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <%= link_to potepan_product_path(related_product.id) do %>
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag(related_product.display_image.attachment(:large)) %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= related_product.name %></h5>
        <h3><%= related_product.display_price %></h3>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<%= render 'layouts/right_section', product_name: @product.name %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% @product.images.each_with_index do |image, index| %>
                  <div class="item <%= "active" if index == 0 %>" data-thumb="<%= index %>">
                    <%= image_tag(image.attachment(:large)) %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% @product.images.each_with_index do |image, index| %>
                    <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
                      <%= image_tag(image.attachment(:small)) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <% if @product.taxons.present? %>
              <ul class="list-inline">
                <li>
                  <%= link_to potepan_category_path(@product.taxons.first.id) do %>
                    <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                  <% end %>
                </li>
              </ul>
            <% end %>  
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
      <%= render partial: "related_product", collection: @related_products %>
    </div>
  </div>
</section>

app/views/potepan/sample/index.html.erb
<!-- BANNER -->
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li>
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
        </li>
      </ul>
    </div>
  </div>
</div>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row featuredCollection">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>人気カテゴリー</h4>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='single_product.html';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-01.jpg", :alt => "feature-collection-image") %>
            <div class="masking"><a href="product_grid_left_sidebar.html" class="btn viewBtn">View Shirts</a></div>
          </div>
          <div class="caption">
            <h4>Shirts</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='single_product.html';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-02.jpg", :alt => "feature-collection-image") %>
            <div class="masking"><a href="product_grid_left_sidebar.html" class="btn viewBtn">View Bags</a></div>
          </div>
          <div class="caption">
            <h4>Bags</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='single_product.html';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-03.jpg", :alt => "feature-collection-image") %>
            <div class="masking"><a href="product_grid_left_sidebar.html" class="btn viewBtn">View Denim</a></div>
          </div>
          <div class="caption">
            <h4>Denim</h4>
          </div>
        </div>
      </div>
    </div>
    <div class="row featuredProducts">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>新着商品</h4>
        </div>
      </div>
      <div class="col-xs-12">
        <div class="owl-carousel featuredProductsSlider">
          <div class="slide">
            <div class="productImage clearfix">
              <%= image_tag("home/featured-product/product-01.jpg", :alt => "featured-product-img") %>
            </div>
            <div class="productCaption clearfix">
              <a href="single_product.html">
                <h5>Mauris efficitur</h5>
              </a>
              <h3>199円</h3>
            </div>
          </div>
          <div class="slide">
            <div class="productImage">
              <%= image_tag("home/featured-product/product-02.jpg", :alt => "featured-product-img") %>
            </div>
            <div class="productCaption">
              <a href="single_product.html">
                <h5>Nulla facilisi</h5>
              </a>
              <h3>149円</h3>
            </div>
          </div>
          <div class="slide">
            <div class="productImage">
              <%= image_tag("home/featured-product/product-03.jpg", :alt => "featured-product-img") %>
            </div>
            <div class="productCaption">
              <a href="single_product.html">
                <h5>Praesent dui felis</h5>
              </a>
              <h3>79円</h3>
            </div>
          </div>
          <div class="slide">
            <div class="productImage">
              <%= image_tag("home/featured-product/product-04.jpg", :alt => "featured-product-img") %>
            </div>
            <div class="productCaption">
              <a href="single_product.html">
                <h5>Cras eu faucibus</h5>
              </a>
              <h3>109円</h3>
            </div>
          </div>
          <div class="slide">
            <div class="productImage">
              <%= image_tag("home/featured-product/product-05.jpg", :alt => "featured-product-img") %>
            </div>
            <div class="productCaption">
              <a href="single_product.html">
                <h5>Mauris lobortis augue</h5>
              </a>
              <h3>199円</h3>
            </div>
          </div>
          <div class="slide">
            <div class="productImage">
              <%= image_tag("home/featured-product/product-06.jpg", :alt => "featured-product-img") %>
            </div>
            <div class="productCaption">
              <a href="single_product.html">
                <h5>Suspendisse suscipit</h5>
              </a>
             <h3>149円</h3>
            </div>
          </div>
          <div class="slide">
            <div class="productImage">
              <%= image_tag("home/featured-product/product-07.jpg", :alt => "featured-product-img") %>
            </div>
            <div class="productCaption">
              <a href="single_product.html">
                <h5>Praesent a augue</h5>
              </a>
              <h3>79円</h3>
            </div>
          </div>
          <div class="slide">
            <div class="productImage">
              <%= image_tag("home/featured-product/product-09.jpg", :alt => "featured-product-img") %>
            </div>
            <div class="productCaption">
              <a href="single_product.html">
                <h5>Cras vel augue</h5>
              </a>
              <h3>109円</h3>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/partners_logo' %>